### ISSUE TITLE
Launching meteor does not show any error logs.

### ISSUE THREAD

**Issue by mudum** [PEM--/meteor-helper#45] opened 2015-09-26 15:35 UTC
This may be windows' fault. I am on windows 10 64-bit. When I launch my app using atom, it doesn't show anything except for the warning icon continuing to blink. Although it can run when just using the command prompt.

**Comment by PEM--** [comment] 2015-09-26 15:54
It's also confirmed on OSX. Something has changed in the last Atom's update. Weird.

Thanks for the warning.

**Comment by sdinesh86** [comment] 2015-09-27 11:51
open and close developer tools once you launch meteor, the logs will start to show up.

**Comment by mudum** [comment] 2015-09-27 14:51
It now gives me the tasklist error

**Comment by cecet** [comment] 2015-10-22 19:14
Please see if mongo process was killed properly, solved the same problem for me – it was due to wrongly seth paths and application crashing before killing it. 

About those paths – I found that if I already have meteor directory added to system `PATH` I coud just  set "Meteor Path" in extension settings to:

```
meteor.bat
```

and it just worked.

(Please note that you do not need to create or modify any file on your filesystem in this solution)

And if this doesn't work then probably there is no meteor directory in system path variable – you can fix it by adding it permanently by typing in command line:

```
SET PATH=%PATH%;C:\Users\username\AppData\Local\.meteor\
```

(You can remove it later if you want of course, but it's really good thing to have; and if you want to use several different versions of meteor, I would suggest just creating many .bat files pointing to them in the meteor directory that was added to path, and just edit their contents to create/overwrite default meteor.bat file to point to different installs inside, and later just delete default meteor.bat, to now use unknown installation in case of something crashing... but these are just my loose thoughts).

**Comment by zgudino** [comment] 2015-10-26 13:06
@sdinesh86 Thanks! That solve the problem

**Comment by PEM--** [comment] 2015-10-27 08:13
Fixed in 0.27.0.

**Closed by PEM--** 2015-10-27 08:13 UTC
Labels: bug

**Comment by mudum** [comment] 2015-10-29 04:21
excellent
